# Generated by Django 5.2.4 on 2025-07-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('is_attended', models.BooleanField(default=False)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
